[project]
name = "bank-statement-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jason Farrar", email = "farrar.jason1@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dacite>=1.9.2",
    "pdfplumber>=0.11.7",
    "polars>=1.35.1",
    "xlsxwriter>=3.2.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "memory-profiler>=0.61.0",
    "ruff>=0.14.2",
    "scalene>=1.5.55",
]

[tool.ruff]
line-length = 140
target-version = "py310"
unfixable = ["F401"]
